<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Santri_model extends CI_Model
{

    public $table = 'santri';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama_santri', $q);
	$this->db->or_like('id_unit', $q);
	$this->db->or_like('id_angkatan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
    //    $this->db->order_by($this->id, $this->order);
    //    $this->db->like('id', $q);
	//$this->db->or_like('nama_santri', $q);
	//$this->db->or_like('id_unit', $q);
	//$this->db->or_like('id_angkatan', $q);
	//$this->db->limit($limit, $start);

        $this->db->select('santri.*, master_unit.nama_unit, tahun_angkatan.tahun_angkatan');
        $this->db->join('master_unit', 'master_unit.id = santri.id_unit');
        $this->db->join('tahun_angkatan', 'tahun_angkatan.id = santri.id_angkatan');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Santri_model.php */
/* Location: ./application/models/Santri_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-12 10:31:52 */
/* http://harviacode.com */