<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sub_kategori_model extends CI_Model
{

    public $table = 'sub_kategori';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    $this->db->select('sub_kategori.*, master_unit.nama_unit, tahun_angkatan.tahun_angkatan, tahun_ajaran.tahun_ajar, kategori_pembayaran.nama_kategori');
    $this->db->join('kategori_pembayaran', 'kategori_pembayaran.id = sub_kategori.id_kategori');
    $this->db->join('master_unit', 'master_unit.id = sub_kategori.id_unit');
    $this->db->join('tahun_angkatan', 'tahun_angkatan.id = sub_kategori.id_tahun_angkatan');
    $this->db->join('tahun_ajaran', 'tahun_ajaran.id = sub_kategori.id_tahun_ajaran');

	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->select('sub_kategori.*, master_unit.nama_unit, tahun_angkatan.tahun_angkatan, tahun_ajaran.tahun_ajar, kategori_pembayaran.nama_kategori');
    $this->db->join('kategori_pembayaran', 'kategori_pembayaran.id = sub_kategori.id_kategori');
    $this->db->join('master_unit', 'master_unit.id = sub_kategori.id_unit');
    $this->db->join('tahun_angkatan', 'tahun_angkatan.id = sub_kategori.id_tahun_angkatan');
    $this->db->join('tahun_ajaran', 'tahun_ajaran.id = sub_kategori.id_tahun_ajaran');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sub_kategori_model.php */
/* Location: ./application/models/Sub_kategori_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-16 11:23:46 */
/* http://harviacode.com */