<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sub_kategori_model extends CI_Model
{

    public $table = 'sub_kategori';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('nama_sub_kategori', $q);
	$this->db->or_like('nilai_bayar', $q);
	$this->db->or_like('id_tahun_angkatan', $q);
	$this->db->or_like('pembayaran', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->select('sub_kategori.*, groups.name, kategori_pembayaran.nama_kategori');
        $this->db->join('groups', 'groups.id = sub_kategori.id_tahun_angkatan', 'left');
        $this->db->join('kategori_pembayaran', 'kategori_pembayaran.id = sub_kategori.id_kategori', 'left');
	    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sub_kategori_model.php */
/* Location: ./application/models/Sub_kategori_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-27 00:17:59 */
/* http://harviacode.com */