<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tahun_ajaran_model extends CI_Model
{

    public $table = 'tahun_ajaran';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tahun_ajar', $q);
	$this->db->or_like('thajar_mulai', $q);
	$this->db->or_like('thajar_selesai', $q);
	$this->db->or_like('pts', $q);
	$this->db->or_like('pas', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('tahun_ajar', $q);
	$this->db->or_like('thajar_mulai', $q);
	$this->db->or_like('thajar_selesai', $q);
	$this->db->or_like('pts', $q);
	$this->db->or_like('pas', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getActiveThAjar($id = null)
    {
        if ($id != null) {
            $this->db->where('id', $id);
            $thajar = $this->db->get($this->table)->row();    
            $return = $thajar->thajar_mulai;  
        }else{
            $this->db->join('pengaturan', 'pengaturan.tahun_ajaran = tahun_ajaran.id');
            $this->db->where('pengaturan.id', 1); 
            $thajar = $this->db->get($this->table)->row();    
            $return = $thajar->tahun_ajar.'-'.$thajar->semester;       
        }
       

        return $return;
    }

}

/* End of file Tahun_ajaran_model.php */
/* Location: ./application/models/Tahun_ajaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-12 18:47:11 */
/* http://harviacode.com */